name: deepseek-pc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - requests
  - beautifulsoup4
  - lxml
  - pip:
    - openai>=1.60.1
    - python-dotenv>=1.0.0
    - edge-tts>=7.0.0
    - playsound>=1.3.0
    - geopy>=2.4.1
    - keyboard>=0.13.5
    - SpeechRecognition>=3.10.0
    - paramiko>=3.5.1
    - PySimpleGUI>=4.60.5
    - pyaudio>=0.2.14
    - python-dateutil>=2.8.2 